repos:
- repo: local
  hooks:
  - id: clang-format
    name: clang-format
    entry: clang-format -i
    language: system
    files: '\.(c|h)$'
  - id: clang-tidy
    name: clang-tidy
    entry: clang-tidy
    language: system
    pass_filenames: true
    files: '\.(c|h)$'
    args: ['-p', 'build']
