name: GitHub Actions Build
run-name: ${{ github.actor }} triggered a build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Build-on-Ubuntu:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install build deps
        run: |
          ./.codex/setup.sh
      - name: Build p9p
        run: ./INSTALL
      - name: Smoke test with QEMU
        run: qemu-system-x86_64 -nographic -version
  Build-on-macOS:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build p9p
        run: ./INSTALL
